services:
  - type: web
    name: student-assistant-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.10

